In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
df1 = pd.read_csv('삶에_대한_만족감과_정서경험_2021.csv', encoding='cp949')
df2 = pd.read_csv('일자리충분도_2021.csv', encoding='cp949')

In [44]:
# 첫 번째 행을 열 이름으로 설정하고 기존의 열 이름은 삭제
df1.columns = df1.iloc[0]
df1 = df1.drop(0)

# 데이터프레임의 인덱스를 재설정 (기존 인덱스는 삭제)
df1 = df1.reset_index(drop=True)

In [45]:
cols = ['살고있는 지역의 전반적 만족감', '어제 행복 정도','어제 걱정 정도']
df1.drop(columns=cols, axis=1, inplace = True)

In [46]:
df1 = df1.loc[df1['특성별(1)']=='연령별']
df1.drop(columns='특성별(1)', axis=1, inplace=True)

In [47]:
df1

0    특성별(2) 삶에 대한 전반적 만족감
3    29세 이하          5.72
4  30 ~ 39세          6.26
5  40 ~ 49세          6.09
6  50 ~ 59세          5.88
7  60 ~ 69세          5.73
8    70세 이상          5.38

In [48]:
# 첫 번째 행을 열 이름으로 설정하고 기존의 열 이름은 삭제
df2.columns = df2.iloc[0]
df2 = df2.drop(0)

# 데이터프레임의 인덱스를 재설정 (기존 인덱스는 삭제)
df2 = df2.reset_index(drop=True)

In [49]:
df2

0  특성별(1)        특성별(2) 전혀 그렇지 않다 그렇지 않은 편이다  보통이다 그런 편이다 매우 그렇다
0      전체            소계      11.6       49.9  30.0    8.0    0.5
1      성별            남자      10.8       50.3  30.9    7.9    0.1
2      성별            여자      12.5       49.6  29.1    8.0    0.8
3     연령별        29세 이하      22.3       50.5  21.8    5.3    0.0
4     연령별      30 ~ 39세      14.9       52.4  20.2   12.5    0.0
5     연령별      40 ~ 49세      17.1       46.2  25.7   10.5    0.5
6     연령별      50 ~ 59세       8.1       52.9  30.7    7.4    1.0
7     연령별      60 ~ 69세       6.6       49.5  37.8    5.9    0.3
8     연령별        70세 이상       7.1       49.0  34.6    8.7    0.7
9   경제활동별           취업자       9.7       48.3  33.4    8.4    0.2
10  경제활동별         비경제활동      14.0       51.9  25.9    7.4    0.8
11  가구소득별      100만원 미만       7.0       53.3  34.8    4.4    0.5
12  가구소득별  100~200만원 미만      13.7       46.0  33.1    6.5    0.7
13  가구소득별  200~300만원 미만       9.3       49.4  35.2    5.6    0.5
14  가구소득별  300~400만원 미만       8.5       52.5  25.9   12.6    0.5
15  가구소득별  400~500만원 미만      13.0       48.5  28.3    9.7    0.5
16  가구소득별      500만원 이상      21.5       50.0  20.7    7.8    0.0
17  교육정도별          초졸이하       9.3       50.6  33.3    5.9    1.0
18  교육정도별            중졸      10.5       41.6  36.7   10.9    0.3
19  교육정도별            고졸      10.2       53.1  29.2    7.0    0.6
20  교육정도별          대졸이상      15.7       50.8  24.6    8.9    0.0

### 단순 시각화 
- 일자리 충분도

In [60]:
df3 = pd.read_csv('취업자_근로여건_만족도_2022.csv', encoding='cp949')

In [61]:
df3

,특성별(1),특성별(2),2022,2022.1,2022.2,2022.3,2022.4,2022.5,2022.6,2022.7,...,2022.20,2022.21,2022.22,2022.23,2022.24,2022.25,2022.26,2022.27,2022.28,2022.29
0,특성별(1),특성별(2),하는일,하는일,하는일,하는일,하는일,하는일,임금/가구소득(일에 비해),임금/가구소득(일에 비해),...,근무환경,근무환경,근무환경,근무환경,전반적인 만족도,전반적인 만족도,전반적인 만족도,전반적인 만족도,전반적인 만족도,전반적인 만족도
1,특성별(1),특성별(2),매우 불만족 (%),약간 불만족 (%),보통 (%),약간 만족 (%),매우 만족 (%),평균(5점) (점),매우 불만족 (%),약간 불만족 (%),...,보통 (%),약간 만족 (%),매우 만족 (%),평균(5점) (점),매우 불만족 (%),약간 불만족 (%),보통 (%),약간 만족 (%),매우 만족 (%),평균(5점) (점)
2,전체,소계,0.4,14.7,38.2,44.6,2.1,3.33,2.1,21.8,...,43.1,32.2,1.7,3.10,0.4,14.8,46.9,37.1,0.8,3.23
3,성별,남자,0.0,16.0,33.6,48.3,2.1,3.37,1.6,19.9,...,41.3,32.8,1.1,3.09,0.0,14.9,42.3,42.2,0.6,3.28
4,성별,여자,1.0,12.8,45.1,39.1,2.0,3.28,2.9,24.5,...,45.9,31.2,2.7,3.12,1.0,14.5,53.8,29.5,1.3,3.16
5,연령별,29세이하,0.0,20.0,49.9,30.0,0.0,3.10,0.0,40.0,...,47.2,35.0,0.0,3.17,0.0,20.0,56.8,23.2,0.0,3.03
6,연령별,30 ~ 39세,0.0,9.4,31.4,59.2,0.0,3.50,1.7,11.1,...,43.5,38.5,0.0,3.21,0.0,7.7,38.1,54.2,0.0,3.47
7,연령별,40 ~ 49세,0.0,11.2,32.0,53.1,3.7,3.49,2.5,17.4,...,40.9,40.0,3.4,3.26,0.0,7.3,41.5,48.9,2.3,3.46
8,연령별,50 ~ 59세,0.7,16.1,41.3,37.8,4.1,3.28,1.8,20.4,...,36.7,24.9,3.0,2.91,0.7,20.5,45.6,32.3,1.0,3.12
9,연령별,60 ~ 69세,0.0,24.5,36.2,39.3,0.0,3.15,2.6,32.4,...,52.1,26.0,0.0,3.04,0.0,26.4,55.1,18.5,0.0,2.92
10,연령별,70세이상,3.7,9.4,54.6,32.2,0.0,3.15,7.4,26.0,...,58.6,20.9,0.0,2.97,3.7,5.7,72.6,18.0,0.0,3.05
11,경제활동 상태별,취업자,0.4,14.7,38.2,44.6,2.1,3.33,2.1,21.8,...,43.1,32.2,1.7,3.10,0.4,14.8,46.9,37.1,0.8,3.23
12,경제활동 상태별,비경제활동,0.0,0.0,0.0,0.0,0.0,-,0.0,0.0,...,0.0,0.0,0.0,-,0.0,0.0,0.0,0.0,0.0,-
13,소득수준별,100만원 미만,3.2,19.4,68.0,9.4,0.0,2.84,3.2,29.9,...,68.2,8.8,0.0,2.86,0.0,14.8,79.0,6.2,0.0,2.91
14,소득수준별,100~200만원 미만,0.0,15.7,56.2,28.1,0.0,3.12,0.0,15.1,...,51.6,31.8,0.0,3.15,0.0,18.4,71.1,10.5,0.0,2.92
15,소득수준별,200~300만원 미만,0.0,32.1,45.4,21.0,1.4,2.92,3.9,44.0,...,56.0,22.9,1.4,3.04,1.0,25.1,50.3,23.6,0.0,2.97
16,소득수준별,300~400만원 미만,0.0,9.4,42.3,46.9,1.4,3.40,0.0,22.6,...,47.5,30.6,3.3,3.15,0.0,10.4,59.4,28.8,1.4,3.21
17,소득수준별,400~500만원 미만,0.0,9.3,35.4,53.3,2.1,3.48,0.0,19.2,...,38.4,31.6,0.0,2.96,0.0,17.5,37.6,44.9,0.0,3.27
18,소득수준별,500만원 이상,0.5,8.9,25.2,61.9,3.5,3.59,3.2,10.4,...,30.4,42.0,2.4,3.20,0.5,9.2,33.5,55.1,1.7,3.48
19,교육정도별,초졸이하,3.3,11.3,51.9,33.5,0.0,3.16,6.6,25.6,...,56.9,22.7,0.0,2.99,3.3,12.9,71.1,12.7,0.0,2.93
20,교육정도별,중졸,0.0,28.4,52.0,19.6,0.0,2.91,4.8,31.2,...,52.5,8.8,0.0,2.70,0.0,35.0,49.0,16.0,0.0,2.81
21,교육정도별,고졸,0.6,17.5,48.7,31.4,1.7,3.16,2.5,23.4,...,41.0,22.7,0.7,2.83,0.6,17.8,58.0,22.9,0.7,3.05
22,교육정도별,대졸이상,0.0,12.0,29.5,55.8,2.7,3.49,1.2,19.4,...,41.8,41.0,2.6,3.30,0.0,11.0,38.2,49.7,1.1,3.41

In [51]:
# 첫 번째 행을 열 이름으로 설정하고 기존의 열 이름은 삭제
df3.columns = df3.iloc[0]
df3 = df3.drop(0)

# 데이터프레임의 인덱스를 재설정 (기존 인덱스는 삭제)
df3 = df3.reset_index(drop=True)
df3 = df3.loc[df3['특성별(1)']=='연령별']

In [52]:
df3.drop(columns='특성별(1)', axis=1, inplace=True)

In [58]:
df3 = df3.set_index('특성별(2)')

KeyError: "None of ['특성별(2)'] are in the columns"

In [59]:
df3_work =

,하는일,하는일,하는일,하는일,하는일,하는일,임금/가구소득(일에 비해),임금/가구소득(일에 비해),임금/가구소득(일에 비해),임금/가구소득(일에 비해),...,근무환경,근무환경,근무환경,근무환경,전반적인 만족도,전반적인 만족도,전반적인 만족도,전반적인 만족도,전반적인 만족도,전반적인 만족도
특성별(2),,,,,,,,,,,,,,,,,,,,,
29세이하,0.0,20.0,49.9,30.0,0.0,3.10,0.0,40.0,44.6,15.4,...,47.2,35.0,0.0,3.17,0.0,20.0,56.8,23.2,0.0,3.03
30 ~ 39세,0.0,9.4,31.4,59.2,0.0,3.50,1.7,11.1,34.2,50.4,...,43.5,38.5,0.0,3.21,0.0,7.7,38.1,54.2,0.0,3.47
40 ~ 49세,0.0,11.2,32.0,53.1,3.7,3.49,2.5,17.4,39.6,38.2,...,40.9,40.0,3.4,3.26,0.0,7.3,41.5,48.9,2.3,3.46
50 ~ 59세,0.7,16.1,41.3,37.8,4.1,3.28,1.8,20.4,38.9,36.9,...,36.7,24.9,3.0,2.91,0.7,20.5,45.6,32.3,1.0,3.12
60 ~ 69세,0.0,24.5,36.2,39.3,0.0,3.15,2.6,32.4,34.1,30.9,...,52.1,26.0,0.0,3.04,0.0,26.4,55.1,18.5,0.0,2.92
70세이상,3.7,9.4,54.6,32.2,0.0,3.15,7.4,26.0,39.4,27.1,...,58.6,20.9,0.0,2.97,3.7,5.7,72.6,18.0,0.0,3.05